version: '2'
services:
### NGINX ##################################
  nginx:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    restart: "always"
    volumes:
      - "./web/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - "php7"
### PHP-FPM ##################################
  phpfpm:
    image: php:7.2.11-fpm-alpine3.8
    volumes:
      - "~/path/to/dir/:/var/www/html/"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=wakana
      - DB_USERNAME=root
      - DB_PASSWORD=pass

### MYSQL ##################################
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=wakana

networks:
  proxy_net:
    external:
      name: proxy_net