version: '3'
services:
### NGINX ##################################
  nginx:
    image: nginx:alpine
    ports:
    - "801:80"
    volumes:
    - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    - ~/Project/incomelimit/src:/var/www
    depends_on:
    - php-fpm
    environment:
      - VIRTUAL_HOST=gcp.tawn.work
      - VIRTUAL_PORT=801
      - LETSENCRYPT_HOST: cp.tawn.work
      - LETSENCRYPT_EMAIL: buchitaro@live.jp

### PHP-FPM ##################################
  php-fpm:
    build: ./php-fpm
    volumes:
      - ~/Project/incomelimit/src/:/var/www/
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=wakana
      - DB_USERNAME=root
      - DB_PASSWORD=pass

### MYSQL ##################################
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=wakana