version: '3'
services:
### NGINX ##################################
  nginx:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
    - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    - ~/Project/incomelimit/src:/var/www
    depends_on:
    - php-fpm

### PHP-FPM ##################################
  php-fpm:
    build: ./php-fpm/
    volumes:
      - ~/Project/incomelimit/src/:/var/www/
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=wakana
      - DB_USERNAME=root
      - DB_PASSWORD=pass

### MYSQL ##################################
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=wakana

### NODE ##################################
  node:
    image: "node:alpine"
    user: "node"
    environment:
      - NODE_ENV=production
    volumes:
      - ~/Project/incomelimit/src:/home/node/app
    expose:
      - "8081"
    command: "npm start"